# Utiliser l'image Ubuntu la plus récente
FROM ubuntu:latest

# Mise à jour et mise à niveau des paquets
RUN apt-get update && apt-get upgrade -y

# Commande par défaut : afficher "Hello, World!"
CMD ["echo", "Hello, World!"]
